 export const FETCH_DATAS = 'FETCH_DATAS';
 export const GET_ERRORS = 'GET_ERRORS';
 export const TEST_DISPATCH = 'TEST_DISPATCH';
 export const SET_CURRENT_USER = 'SET_CURRENT_USER';
 export const SET_SUCCESS_CREDENTIALS = 'SET_SUCCESS_CREDENTIALS';

